[colors]
bg1 = "#2e3440"
bg2 = "#3b4252"
bg3 = "#434c5e"
bg4 = "#4c566a"
text1 = "#d8dee9"
text2 = "#e5e9f0"
text3 = "#eceff4"
olive = "#8fbcbb"
teal = "#88c0d0"
blue = "#81a1c1"
dark-blue = "#5e81ac"
red = "#bf616a"
orange = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
purple = "#b48ead"
